version: "3"
volumes:
  userpgdata:
services:
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_DB: tss
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5432
    ports:
      - "5435:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080